title = "Rosa AcratağŸ´ğŸŒ¹"
baseURL = "https://www.rosaacrata.xyz/"
theme = "terminal"


# Enable syntax highlighting.
pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


# Number of posts to show in recent posts list (Optional). Defaults to 10.
paginate = 20

[params]
    # dir name of your blog content (default is `content/posts`)
    contentTypeName = "posts"

    # ["orange", "blue", "red", "green", "pink"]
    themeColor = "red"

    # if you set this to 0, only submenu trigger will be visible
    showMenuItems = 2

    # show selector to switch language
    showLanguageSelector = false

    # set theme to full screen width
    fullWidthTheme = true

    # center theme with default width
    centerTheme = false
# Main menu which appears below site header.
[languages]
  [languages.en]
    languageName = "English"
    title = "Rosa AcratağŸ´ğŸŒ¹"
    subtitle = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Rosa AcratağŸ´ğŸŒ¹"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
